### ISSUE TITLE
FLT_TRUE_MIN is truncated to significand 1 and exponent -45

### ISSUE THREAD

**Issue by kridenberg** [cassioneri/teju_jagua#2]
In a pet project me and a friend of mine uses a custom implementation of the to_chars which is powered by a dragonbox instead of Ryu. Now we try to use Teju instead of Dragonbox for different reasons. For that, we have a set of unit tests. And one of our cases is literally the FLT_TRUE_MIN. We have detected, that while Dragonbox, to_chars (Ryu) and std::printf (MSSTD and Libc++) provide a string for 1.4013e-45f (FLT_TRUE_MIN). While Teju effectively decays to something with significand 1 and exponent -45 - truncates all symbols past the dot. I just want to hear your opinion on that case.

**Comment by kridenberg** [comment]
Okay. So, this is kinda stupid from my side to expect true MIN to be actually something different from zero. During the arguing with colleagues, I detected that this was not an issue, and I was misled due to false-claims wich I was bad at verifying. So, I guess I will close that issue.

Cool algorithms. Will use that moment to prise the author for its wonderful job.

**Comment by cassioneri** [comment]
@kridenberg Thanks for your interest in my work and for your kind words.

In this repo, there's a unit-test that scans all finite positive `float`s and compare the outputs of Tejú Jaguá against Ryu and Dragon box. This test shows that the three algorithms produce the very same results, in particular, for `FLT_TRUE_MIN`. So, as you have figured out, this is not an issue.

From your post, I reckon that you manage to build and run this implementation of Tejú Jaguá. That's interesting! As stated in the main page, this is very much a work in progress and the lack of documentation is a main issue which I hope to address rather sooner than later (unfortunately, I have a lot of time constraints!) Hence, I believe that building and running it isn't simple. As far as I know, you are the first person (except me) to have done so. Well done!
